const db = window.getSupabase ? window.getSupabase() : null;
const $ = id => document.getElementById(id);
let events = [];

function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function dateInfo(value){const d=new Date(value);return {day:d.toLocaleDateString('vi-VN',{day:'2-digit'}),month:d.toLocaleDateString('vi-VN',{month:'short'}),full:d.toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'})}}
function eventMatches(e){const q=$('search').value.trim().toLowerCase();const province=$('province').value; if(q&&!`${e.name} ${e.description||''} ${e.organizer||''} ${e.bv_locations?.province||''}`.toLowerCase().includes(q))return false;if(province&&(e.bv_locations?.province||'')!==province)return false;const now=new Date();const start=new Date(e.start_date);const end=new Date(e.end_date||e.start_date);const range=$('range').value;if(range==='upcoming'&&end<now)return false;if(range==='past'&&start>now)return false;return true}
function render(){const list=events.filter(eventMatches);$('mapCount').textContent=`${list.length} sự kiện`;if(!list.length){$('eventList').innerHTML='<div class="event-card"><div class="event-body"><h2>Chưa có sự kiện phù hợp</h2><p class="event-description">Hãy thử đổi bộ lọc hoặc quay lại sau khi lịch triển lãm được cập nhật.</p></div></div>';renderMap([]);return}$('eventList').innerHTML=list.map(e=>{const d=dateInfo(e.start_date);const loc=e.bv_locations||{};const address=[loc.address,loc.district,loc.province].filter(Boolean).join(', ');const maps=loc.latitude&&loc.longitude?`https://www.google.com/maps/search/?api=1&query=${loc.latitude},${loc.longitude}`:'';return `<article class="event-card"><div class="date"><span class="date-day">${d.day}</span><span class="date-month">${d.month}</span></div><div class="event-body"><span class="event-type">${esc(e.event_type)}</span><h2 class="event-name">${esc(e.name)}</h2><p class="event-meta">${esc(d.full)} · ${esc(address||'Đang cập nhật')} ${e.organizer?`· ${esc(e.organizer)}`:''}</p><p class="event-description">${esc(e.description||'Chưa có mô tả.')}</p><div class="actions">${e.official_url?`<a class="official" href="${esc(e.official_url)}" target="_blank" rel="noopener">Trang chính thức</a>`:''}${maps?`<a class="map-link" href="${maps}" target="_blank" rel="noopener">Mở bản đồ</a>`:''}</div></div></article>`}).join('');renderMap(list)}
function renderMap(list){const map=$('map');map.querySelectorAll('.pin').forEach(x=>x.remove());const points=list.filter(e=>e.bv_locations?.latitude&&e.bv_locations?.longitude);if(!points.length){if(!map.querySelector('.map-empty'))map.insertAdjacentHTML('beforeend','<div class="map-empty">Chưa có sự kiện có tọa độ.</div>');return}const empty=map.querySelector('.map-empty');if(empty)empty.remove();const lats=points.map(e=>Number(e.bv_locations.latitude)),lons=points.map(e=>Number(e.bv_locations.longitude));const minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons);points.forEach(e=>{const lat=Number(e.bv_locations.latitude),lon=Number(e.bv_locations.longitude);const left=12+(lon-minLon)/Math.max(maxLon-minLon,.01)*76;const top=12+(maxLat-lat)/Math.max(maxLat-minLat,.01)*76;const pin=document.createElement('div');pin.className='pin';pin.style.left=`${left}%`;pin.style.top=`${top}%`;pin.innerHTML=`<span>${esc(e.name)}</span>`;map.appendChild(pin)})}
async function load(){if(!db){$('eventList').innerHTML='<div class="event-card"><div class="event-body"><h2>Chưa cấu hình Supabase</h2></div></div>';return}const {data,error}=await db.from('bv_events').select('*, bv_locations(name,address,province,district,latitude,longitude)').eq('status','PUBLISHED').order('start_date',{ascending:true});if(error){$('eventList').innerHTML=`<div class="event-card"><div class="event-body"><h2>Không tải được lịch</h2><p>${esc(error.message)}</p></div></div>`;return}events=data||[];const provinces=[...new Set(events.map(e=>e.bv_locations?.province).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'vi'));$('province').innerHTML='<option value="">Tất cả tỉnh/thành</option>'+provinces.map(p=>`<option>${esc(p)}</option>`).join('');render()}
$('search').addEventListener('input',render);$('province').addEventListener('change',render);$('range').addEventListener('change',render);load();