-- BONSAI VIET - content database for Supabase/PostgreSQL
-- Run after the existing auth setup. This schema uses auth.users for accounts.

create extension if not exists pgcrypto;

create table if not exists public.bv_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Người yêu cây',
  avatar_url text,
  role text not null default 'USER' check (role in ('USER','AUTHOR','ARTIST','MODERATOR','EDITOR','ADMIN')),
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bv_locations (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  province text,
  district text,
  latitude numeric(10,7),
  longitude numeric(10,7),
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.bv_plants (
  id bigint generated by default as identity primary key,
  name text not null,
  scientific_name text,
  slug text not null unique,
  short_description text,
  description text,
  origin text,
  growth_rate text,
  difficulty text check (difficulty in ('BEGINNER','INTERMEDIATE','ADVANCED')),
  sunlight text,
  watering text,
  soil text,
  root_characteristics text,
  trunk_characteristics text,
  pruning_notes text,
  wiring_notes text,
  propagation_notes text,
  featured_image text,
  status text not null default 'DRAFT' check (status in ('DRAFT','PUBLISHED','ARCHIVED','HIDDEN')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bv_techniques (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  category text,
  difficulty text check (difficulty in ('BEGINNER','INTERMEDIATE','ADVANCED')),
  description text,
  tools_required text,
  best_season text,
  safety_notes text,
  common_mistakes text,
  expert_tips text,
  status text not null default 'DRAFT' check (status in ('DRAFT','PUBLISHED','ARCHIVED','HIDDEN')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bv_forms (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  characteristics text,
  structure text,
  difficulty text check (difficulty in ('BEGINNER','INTERMEDIATE','ADVANCED')),
  status text not null default 'DRAFT' check (status in ('DRAFT','PUBLISHED','ARCHIVED','HIDDEN')),
  created_at timestamptz not null default now()
);

create table if not exists public.bv_styles (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  style_type text,
  country text,
  region text,
  description text,
  history text,
  characteristics text,
  philosophy text,
  status text not null default 'DRAFT' check (status in ('DRAFT','PUBLISHED','ARCHIVED','HIDDEN')),
  created_at timestamptz not null default now()
);

create table if not exists public.bv_artists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  slug text not null unique,
  biography text,
  experience_years integer,
  specialization text,
  philosophy text,
  achievements text,
  location_id bigint references public.bv_locations(id) on delete set null,
  verified boolean not null default false,
  status text not null default 'DRAFT' check (status in ('DRAFT','PUBLISHED','ARCHIVED','HIDDEN')),
  created_at timestamptz not null default now()
);

create table if not exists public.bv_works (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  artist_id bigint references public.bv_artists(id) on delete set null,
  plant_id bigint not null references public.bv_plants(id) on delete restrict,
  form_id bigint references public.bv_forms(id) on delete set null,
  style_id bigint references public.bv_styles(id) on delete set null,
  name text not null,
  slug text not null unique,
  description text,
  estimated_age integer,
  height_cm numeric(8,2),
  width_cm numeric(8,2),
  trunk_diameter_cm numeric(8,2),
  origin text,
  creation_story text,
  technique_notes text,
  status text not null default 'DRAFT' check (status in ('DRAFT','PUBLISHED','ARCHIVED','HIDDEN')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bv_events (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  event_type text not null,
  organizer text,
  location_id bigint references public.bv_locations(id) on delete set null,
  start_date timestamptz not null,
  end_date timestamptz,
  registration_url text,
  official_url text,
  contact text,
  status text not null default 'DRAFT' check (status in ('DRAFT','PUBLISHED','ARCHIVED','HIDDEN')),
  created_at timestamptz not null default now()
);

create table if not exists public.bv_articles (
  id bigint generated by default as identity primary key,
  author_id uuid references auth.users(id) on delete set null,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text not null,
  article_type text not null,
  featured_image text,
  status text not null default 'DRAFT' check (status in ('DRAFT','PUBLISHED','ARCHIVED','HIDDEN')),
  published_at timestamptz,
  meta_title text,
  meta_description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bv_plant_techniques (
  plant_id bigint references public.bv_plants(id) on delete cascade,
  technique_id bigint references public.bv_techniques(id) on delete cascade,
  difficulty text,
  notes text,
  primary key (plant_id, technique_id)
);

create table if not exists public.bv_plant_forms (
  plant_id bigint references public.bv_plants(id) on delete cascade,
  form_id bigint references public.bv_forms(id) on delete cascade,
  notes text,
  primary key (plant_id, form_id)
);

create table if not exists public.bv_plant_styles (
  plant_id bigint references public.bv_plants(id) on delete cascade,
  style_id bigint references public.bv_styles(id) on delete cascade,
  notes text,
  primary key (plant_id, style_id)
);

create index if not exists bv_plants_status_idx on public.bv_plants(status);
create index if not exists bv_plants_slug_idx on public.bv_plants(slug);
create index if not exists bv_techniques_status_idx on public.bv_techniques(status);
create index if not exists bv_articles_published_idx on public.bv_articles(status, published_at desc);
create index if not exists bv_events_date_idx on public.bv_events(start_date);

alter table public.bv_profiles enable row level security;
alter table public.bv_plants enable row level security;
alter table public.bv_techniques enable row level security;
alter table public.bv_forms enable row level security;
alter table public.bv_styles enable row level security;
alter table public.bv_artists enable row level security;
alter table public.bv_works enable row level security;
alter table public.bv_events enable row level security;
alter table public.bv_articles enable row level security;

-- Public visitors can read published knowledge. Writes are reserved for admins/editors.
drop policy if exists "Public read published plants" on public.bv_plants;
create policy "Public read published plants" on public.bv_plants for select using (status = 'PUBLISHED');

drop policy if exists "Public read published techniques" on public.bv_techniques;
create policy "Public read published techniques" on public.bv_techniques for select using (status = 'PUBLISHED');

drop policy if exists "Public read published forms" on public.bv_forms;
create policy "Public read published forms" on public.bv_forms for select using (status = 'PUBLISHED');

drop policy if exists "Public read published styles" on public.bv_styles;
create policy "Public read published styles" on public.bv_styles for select using (status = 'PUBLISHED');

drop policy if exists "Public read published artists" on public.bv_artists;
create policy "Public read published artists" on public.bv_artists for select using (status = 'PUBLISHED');

drop policy if exists "Public read published works" on public.bv_works;
create policy "Public read published works" on public.bv_works for select using (status = 'PUBLISHED');

drop policy if exists "Public read published events" on public.bv_events;
create policy "Public read published events" on public.bv_events for select using (status = 'PUBLISHED');

drop policy if exists "Public read published articles" on public.bv_articles;
create policy "Public read published articles" on public.bv_articles for select using (status = 'PUBLISHED');

-- Admin/editor policy helper. The role is stored in bv_profiles and checked against auth.uid().
create or replace function public.bv_is_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.bv_profiles
    where id = auth.uid() and role in ('ADMIN','EDITOR')
  );
$$;

drop policy if exists "Editors manage plants" on public.bv_plants;
create policy "Editors manage plants" on public.bv_plants for all using (public.bv_is_editor()) with check (public.bv_is_editor());

drop policy if exists "Editors manage techniques" on public.bv_techniques;
create policy "Editors manage techniques" on public.bv_techniques for all using (public.bv_is_editor()) with check (public.bv_is_editor());

drop policy if exists "Editors manage forms" on public.bv_forms;
create policy "Editors manage forms" on public.bv_forms for all using (public.bv_is_editor()) with check (public.bv_is_editor());

drop policy if exists "Editors manage styles" on public.bv_styles;
create policy "Editors manage styles" on public.bv_styles for all using (public.bv_is_editor()) with check (public.bv_is_editor());

drop policy if exists "Editors manage artists" on public.bv_artists;
create policy "Editors manage artists" on public.bv_artists for all using (public.bv_is_editor()) with check (public.bv_is_editor());

drop policy if exists "Editors manage works" on public.bv_works;
create policy "Editors manage works" on public.bv_works for all using (public.bv_is_editor()) with check (public.bv_is_editor());

drop policy if exists "Editors manage events" on public.bv_events;
create policy "Editors manage events" on public.bv_events for all using (public.bv_is_editor()) with check (public.bv_is_editor());

drop policy if exists "Editors manage articles" on public.bv_articles;
create policy "Editors manage articles" on public.bv_articles for all using (public.bv_is_editor()) with check (public.bv_is_editor());
